### ISSUE TITLE
Angular can't find constructors

### ISSUE THREAD

**Issue by Nirostar** [commenthol/date-holidays#244]
Hi, I can't get date-holidays working with angular. I get date_holidays_1.default is not a constructor. What did I do wrong.

I provided a codesandbox:
https://codesandbox.io/s/date-holidays-1vgtv?file=/src/app/app.component.ts

**Comment by commenthol** [comment]
Hi @Nirostar, 
This is indeed interesting. Thanks for posting the issue.
It looks to me that angular does not yet understand the npm ecmascript module exports.
In order to get things to work I'll need to update a couple of packages which depend on date-holidays. This will take some time.
Keep fingers crossed that this hopefully sorts out...

**Comment by commenthol** [comment]
Hi @Nirostar,
Hope that the issues are fixed with 3.5.0. Please note the changes with the types import. 
```ts
import Holidays, {HolidaysTypes} from 'date-holidays';
```
Thanks again for providing a sample project, such to find the issue.

**Comment by jp928** [comment]
@commenthol Thanks for your efforts on this. However, it seems like 3.5.0 doesn't fix this issue.
I am using NestJS which could be similar as Angular.

**Comment by jp928** [comment]
I tested on @Nirostar 's code base it works.
So, it could be something wrong on my end.
